language: dart

dart:
  - dev

dart_task:
  - test: --platform vm
  - test: --platform firefox -j 1
  - dartanalyzer
  - dartfmt

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
