language: dart

dart:
- be/raw/latest

dart_task:
- test
- dartfmt
- dartanalyzer: --fatal-infos --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master, null_safety]

# Incremental pub cache and builds.
cache:
  directories:
  - $HOME/.pub-cache
