name: collection
version: 1.14.12-dev

description: Collections and utilities functions and classes related to collections.
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/collection

environment:
  # Required for Dart 2.0 collection changes.
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_web_compilers: ^1.0.0
  test: ^1.0.0
